// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.CirclesRoute = Ember.Route.extend({
    setupController: function(controller) {
      controller.set('allCircles', this.store.find('circle'));
      return controller.set('allContacts', this.store.find('contact'));
    },
    renderTemplate: function() {
      return this.render('circles', {
        into: 'application'
      });
    }
  });

}).call(this);
