// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.ProfilesRoute = Ember.Route.extend({
    setupController: function(controller) {
      return this.get('store').find('onion', 1).then(function(_onion) {
        return controller.set('allProfiles', _onion.get('profiles'));
      });
    },
    renderTemplate: function() {
      return this.render('profiles', {
        into: 'application'
      });
    }
  });

}).call(this);
