// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.ContactsEditController = Ember.ObjectController.extend({
    actions: {
      deleteContact: function() {
        var contact;
        contact = this.get('model');
        contact.deleteRecord();
        return contact.save();
      },
      blockContact: function() {
        var contact;
        contact = this.get('model');
        contact.set('status', 0);
        return contact.save();
      },
      unblockContact: function() {
        var contact;
        contact = this.get('model');
        contact.set('status', 2);
        return contact.save();
      },
      acceptContact: function() {
        var contact;
        contact = this.get('model');
        contact.set('status', 3);
        contact.save();
        return this.trigger(contact.id);
      },
      followContact: function() {
        var contact;
        contact = this.get('model');
        contact.set('status', 4);
        return contact.save();
      },
      updateAlias: function() {
        var contact;
        contact = this.get('model');
        return contact.save().then((function() {}), function() {
          return contact.reload();
        });
      }
    },
    trigger: function(contact_id) {
      var formData, token, user, xhr;
      user = Ember.$.cookie('auth_user');
      token = Ember.$.cookie('auth_token');
      xhr = new XMLHttpRequest();
      xhr.open("post", "/trigger", true);
      xhr.setRequestHeader('Auth-User', user);
      xhr.setRequestHeader('Auth-Token', token);
      formData = new FormData();
      formData.append('contactId', contact_id);
      return xhr.send(formData);
    }
  });

}).call(this);
