// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.PostController = Ember.ObjectController.extend({
    commentsVisible: false,
    publicComment: true,
    showComments: (function() {
      return this.get('commentCount') > 0 && this.get('commentsVisibility');
    }).property('commentCount', 'commentsVisibility'),
    hasComments: (function() {
      return this.get('commentCount') > 0;
    }).property('commentCount'),
    commentButtonLabel: (function() {
      var label;
      label = "";
      label += this.get('commentsVisibility') ? "Hide " : "Show ";
      label += "Comments ";
      return label += "(" + this.get('commentCount') + ")";
    }).property('commentCount', 'commentsVisibility'),
    commentCount: (function() {
      return this.get('comments').get('length');
    }).property('comments.@each'),
    actions: {
      createComment: function() {
        var message, parent;
        parent = this.get('model');
        message = this.get('commentMessage');
        if (!message.trim()) {
          return;
        }
        return this.store.find('originator', 1).then((function(_this) {
          return function(originator) {
            return _this.store.find('author', 1).then(function(author) {
              var comment;
              comment = _this.store.createRecord('comment', {
                author: author,
                originator: originator,
                parent: parent,
                message: message,
                ttl: _this.get('publicComment') ? 2 : 1
              });
              return parent.get('comments').then(function(comments) {
                comments.pushObject(comment);
                return comment.save().then(function() {
                  _this.set('commentMessage', "");
                  return parent.reload();
                }, function() {
                  return alert("Something went wrong");
                });
              });
            });
          };
        })(this));
      },
      showCommentsSection: function() {
        return this.set('commentsVisible', true);
      },
      hideCommentsSection: function() {
        return this.set('commentsVisible', false);
      },
      deletePost: function() {
        var post;
        post = this.get('model');
        post.get('comments').then((function(_this) {
          return function(_comments) {
            return _comments.forEach(function(_comment) {
              _comment.deleteRecord();
              return _comment.save();
            });
          };
        })(this));
        post.deleteRecord();
        return post.save();
      },
      togglePublicComment: function() {
        return this.set('publicComment', !this.get('publicComment'));
      }
    }
  });

}).call(this);
