// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.ProfileController = Ember.ObjectController.extend({
    circlesFromModel: (function() {
      return this.get('model.circles');
    }).property('model.circles'),
    selectedCircles: null,
    isPicture: (function() {
      return this.get('model.key') === "picture";
    }).property('model.key'),
    isHidden: (function() {
      var key;
      key = this.get('model.key');
      return key === "picture" || key === "";
    }).property('model.key'),
    actions: {
      addCircle: function(circleId) {
        var currentCircles, model;
        model = this.get('model');
        currentCircles = this.get('model.circles');
        return this.store.find('circle', circleId).then((function(_this) {
          return function(circle) {
            currentCircles.pushObject(circle);
            return model.save();
          };
        })(this));
      },
      removeCircle: function(circleId) {
        return this.get('model').get('circles').then((function(_this) {
          return function(_circles) {
            var circle;
            circle = _circles.findBy('id', circleId.toString());
            _circles.removeObject(circle);
            return _this.get('model').save();
          };
        })(this));
      },
      deleteProfile: function() {
        var profile;
        profile = this.get('model');
        profile.deleteRecord();
        profile.save();
        return this.store.find('onion', 1).then((function(_this) {
          return function(_myOnion) {
            return _myOnion.get('profiles').then(function(_profiles) {
              return _profiles.removeObject(profile);
            });
          };
        })(this));
      }
    }
  });

}).call(this);
