// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.Store = DS.Store.extend({
    adapter: DS.RESTAdapter.reopen({
      host: 'http://' + location.host + '/api',
      ajaxError: function(jqXHR) {
        var error;
        error = this._super(jqXHR);
        if (jqXHR && jqXHR.status === 401) {
          return $('#logoutButton').click();
        }
      }
    })
  });

}).call(this);
