// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.Author = DS.Model.extend({
    onion: DS.attr('string'),
    posts: DS.hasMany('post', {
      async: true
    }),
    contact: DS.belongsTo('contact', {
      async: true
    })
  });

}).call(this);
