// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.Contact = DS.Model.extend({
    onion: DS.belongsTo('onion', {
      async: true
    }),
    circles: DS.hasMany('circle', {
      async: true
    }),
    nickname: DS.attr('string'),
    alias: DS.attr('string'),
    trust: DS.attr('number'),
    status: DS.attr('number'),
    request_message: DS.attr('string'),
    isSelfContact: (function() {
      return this.get("id") <= "1";
    }).property("id"),
    isSelectedContacts: (function() {
      var contact;
      console.log("spam");
      contact = this.get('model');
      console.log(contact.id);
      console.log(selectedContact.id);
      return contact.id === selectedContact.id;
    }),
    userCreatedCircles: Ember.computed.filterBy('circles', 'creator', 1),
    isBlocked: (function() {
      return this.get("status") === 0;
    }).property("status"),
    isOpen: (function() {
      return this.get("status") === 1;
    }).property("status"),
    isPending: (function() {
      return this.get("status") === 2;
    }).property("status"),
    isSuccess: (function() {
      return this.get("status") === 3;
    }).property("status"),
    isFollowing: (function() {
      return this.get("status") === 4;
    }).property("status"),
    profilePictureId: DS.attr('number'),
    profilePicture: "img/no_profile_picture.jpg",
    profilePictureCall: (function() {
      var profile;
      if (this.get('profilePictureId') > 0) {
        profile = this.store.find('profile', this.get('profilePictureId')).then((function(_this) {
          return function(_profile) {
            return _this.set('profilePicture', "data:image/jpg;base64," + _profile.get('value'));
          };
        })(this));
      } else {
        this.set('profilePicture', "img/no_profile_picture.jpg");
      }
      return "";
    }).property('profilePictureId')
  });

}).call(this);
