// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.Profile = DS.Model.extend({
    key: DS.attr('string'),
    value: DS.attr('string'),
    onion: DS.belongsTo('onion', {
      async: true
    }),
    circles: DS.hasMany('circle', {
      async: true
    }),
    isHidden: (function() {
      var key;
      key = this.get('key');
      return key === "picture" || key === "";
    }).property('key')
  });

}).call(this);
