// Generated by CoffeeScript 1.7.1
(function() {
  marked.setOptions({
    renderer: new marked.Renderer(),
    gfm: true,
    tables: true,
    breaks: false,
    pedantic: false,
    sanitize: true,
    smartLists: true,
    smartypants: false
  });

  Ember.Handlebars.helper("format-markdown", function(input) {
    return new Handlebars.SafeString(marked(input));
  });

}).call(this);
