// Generated by CoffeeScript 1.7.1
(function() {
  SecSocNet.ProfileCircleDrop = Ember.View.extend({
    templateName: 'profile-circles-drop',
    dragOver: function(ev) {
      return ev.preventDefault();
    },
    drop: function(ev) {
      var circle, controller, id, profile;
      id = ev.dataTransfer.getData('text/data');
      controller = this.get('controller');
      circle = controller.get('circles').filterBy('id', id)[0];
      profile = controller.get('profiles').filterBy('id', this.get('content.id'))[0];
      return profile.get('circles').then(function(_circles) {
        _circles.pushObject(circle);
        return profile.save().then((function() {}), function() {
          return profile.reload();
        });
      });
    }
  });

}).call(this);
